language: node_js
sudo: required
cache:
  yarn: true
  directories:
    - node_modules
node_js:
  - "8"
install:
  - npm install -g yarn --cache-min 999999999
script:
  - yarn install
  - yarn build
  - cp .travis.yml build
  - touch build/.nojekyll
branches:
  only:
  - master
deploy:
  provider: pages
  skip-cleanup: true
  target-branch: gh-pages
  local-dir: build
  github-token: $GITHUB_TOKEN
  keep-history: false
  on:
    branch: master
